# netlify.toml

[build]
  # The build command for your frontend (React)
  command = "npm run build"  # Replace with your actual build command

  # The directory where your frontend build output is located
  publish = "frontend/build"  # Replace with your actual build folder path

  # Build environment variables (if needed)
  # environment = { REACT_APP_API_URL = "/.netlify/functions/api" }  # Replace with your API endpoint

[[redirects]]
  # Redirect all paths to the index.html for client-side routing (React Router)
  from = "/*"
  to = "/index.html"
  status = 200  # Use 200 for client-side routing

# Define build settings for your backend (Node.js, Express, etc.) if needed
# Example:
# [build]
#   command = "npm run build"  # Replace with your backend build command
#   publish = "backend/build"  # Replace with your backend build folder path
