# netlify.toml

[build]
  # The build command for your frontend (React)
  command = "npm run build"  # Replace with your actual build command

  # The directory where your frontend build output is located
  publish = "build"  # Replace with your actual build folder path

  # Build environment variables (if needed)
  # environment = { REACT_APP_API_URL = "/.netlify/functions/api" }  # Replace with your API endpoint

